basePath: /api/v1
definitions:
  response.Base:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
  services.UserLoginReq:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  services.UserRegisterReq:
    properties:
      password:
        type: string
      passwordConfirm:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: 技术栈 Gin + Go-Micro + Gorm + gRPC
  title: 微服务 API
  version: 0.0.1
paths:
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: json参数
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/services.UserLoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: 返回体
          schema:
            $ref: '#/definitions/response.Base'
      summary: 登录接口
      tags:
      - 用户模块
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: json参数
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/services.UserRegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: 返回体
          schema:
            $ref: '#/definitions/response.Base'
      summary: 注册接口
      tags:
      - 用户模块
  /test:
    get:
      consumes:
      - application/json
      parameters:
      - description: 当前页第几页
        in: query
        name: page
        type: integer
      - description: 当前页的大小
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 返回体
          schema:
            $ref: '#/definitions/response.Base'
      summary: test 接口
      tags:
      - test
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
